a = str("Hello World")
print(a)
print(type(a))
b = int(20)
print(b)
print(type(b))
c = float(20.5)
print(c)
print(type(c))
d = complex(1j)
print(d)
print(type(d))
e = list(("acdc", "blur", "megadeath"))
print(e)
print(type(e))
f = tuple(("metallica", "linkin park", "the beatles"))
print(f)
print(type(f))
g = range(6)
print(g)
print(type(g))
h = dict(name="elliot", age=15)
print(h)
print(type(h))
i = set(("foo fighters", "abba", "oasis"))
print(i)
print(type(i))
j = frozenset(("nirvana", "queen", "the rolling stones"))
print(j)
print(type(j))
k = bool(5)
print(k)
print(type(k))
l = bytes(5)
print(l)
print(type(l))
m = bytearray(5)
print(m)
print(type(m))
n = memoryview(bytes(5))
print(n)
print(type(n))
